import { build, stop } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { JSDOM } from 'jsdom';
import { initialDeck } from '../lib/studio.ts';
const result = await build({entryPoints:['lib/html-export.ts'],bundle:true,platform:'browser',format:'esm',write:false,define:{'process.env.NODE_ENV':JSON.stringify('production')},plugins:[{name:'raw',setup(b){b.onResolve({filter:/\?raw$/},args=>({path:args.path.startsWith('@/')?resolve(process.cwd(),args.path.slice(2).replace(/\?raw$/,'')):resolve(args.resolveDir,args.path.replace(/\?raw$/,'')),namespace:'raw'}));b.onLoad({filter:/.*/,namespace:'raw'},async args=>({contents:await readFile(args.path,'utf8'),loader:'text'}));}}],alias:{'@':process.cwd()},logLevel:'silent'});
const {exportHtml}=await import('data:text/javascript;base64,'+Buffer.from(result.outputFiles[0].text).toString('base64'));
const html=await (await exportHtml(initialDeck)).text();
await writeFile('qa/buddy-silhouette.html',html);
const dom=new JSDOM(html,{runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window;
w.ResizeObserver=class{observe(){}};
w.matchMedia=()=>({matches:true});
w.CSS={escape:s=>s};
const canvas=w.document.getElementById('buddy-motion');
const script=w.document.querySelector('script[type="module"]').textContent;
if(script.includes('import '))throw new Error('Unexpected offline import');
w.eval(script.replace(/^export /gm,''));
if(w.document.getElementById('counter').textContent!=='1 / 3')throw new Error('Export did not run');
w.document.getElementById('next').click();
if(canvas.dataset.motionPhase!=='idle')throw new Error('Reduced motion did not finish');
console.log(JSON.stringify({bytes:html.length,scenes:w.document.querySelectorAll('.offline-scene').length,standalone:true,executed:true,reducedMotion:true,externalImports:false}));
dom.window.close();await stop();process.exit(0);
