import { createRequire } from 'node:module';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
const require = createRequire('/Users/hugo/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/package.json');
const { chromium } = require('playwright');
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1600, height: 1050 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
await mkdir(new URL('checks/', import.meta.url), { recursive: true });
await page.goto('http://127.0.0.1:4175/buddy-comparatif.html');
await page.waitForLoadState('networkidle');
await page.screenshot({ path: new URL('checks/initial.png', import.meta.url).pathname, fullPage: true });
for (const time of [1500, 3200, 6100, 8300, 11000, 14400]) {
  await page.locator('#timeline').evaluate((input, value) => { input.value = String(value); input.dispatchEvent(new Event('input', { bubbles: true })); }, time);
  await page.screenshot({ path: new URL(`checks/frame-${time}.png`, import.meta.url).pathname, fullPage: true });
}
const seek = async time => page.locator('#timeline').evaluate((input, value) => { input.value = String(value); input.dispatchEvent(new Event('input', { bubbles: true })); }, time);
// Validate the rendered SVG endpoints against the actual rendered pencil.
for (let t = 7460; t < 12950; t += 53) {
  await seek(t);
  const results = await page.locator('.variant > svg').evaluateAll(svgs => svgs.map(svg => {
    const ink = svg.querySelector('[data-ink]:last-of-type') || [...svg.querySelectorAll('[data-ink]')].at(-1);
    const lastInk = [...svg.querySelectorAll('[data-ink]')].at(-1);
    if (svg.dataset.penDown !== 'true' || !ink) return { down: false };
    const end = lastInk.getPointAtLength(lastInk.getTotalLength());
    const nib = svg.querySelector('[data-nib]');
    return { down: true, distance: Math.hypot(end.x - Number(nib.getAttribute('cx')), end.y - Number(nib.getAttribute('cy'))) };
  }));
  results.forEach(result => { if (result.down) assert.ok(result.distance < .01, 'rendered ink is at the nib'); });
}
await seek(14400);
assert.equal(await page.locator('[data-ink]').count(), 24);
await seek(0);
assert.equal(await page.locator('[data-ink]').count(), 0, 'seeking back clears future ink');
await page.locator('#play').click();
await page.waitForTimeout(350);
await page.locator('#play').click();
const paused = await page.locator('#timeline').inputValue();
const frozen = await page.locator('[data-scene]').evaluateAll(nodes => nodes.map(node => node.innerHTML));
await page.waitForTimeout(150);
assert.equal(await page.locator('#timeline').inputValue(), paused, 'pause freezes time');
assert.deepEqual(await page.locator('[data-scene]').evaluateAll(nodes => nodes.map(node => node.innerHTML)), frozen, 'pause freezes all three scenes');
assert.ok(Number(paused) > 100, 'play advances');
await page.locator('[data-speed="0.25"]').click();
assert.equal(await page.locator('[data-speed="0.25"]').getAttribute('aria-pressed'), 'true');
await seek(0);
await page.locator('#play').click();
await page.waitForTimeout(350);
await page.locator('#play').click();
const slow = Number(await page.locator('#timeline').inputValue());
assert.ok(slow < Number(paused) * .6 && slow > 20, 'quarter speed advances more slowly');
await page.locator('[data-seek="5250"]').click();
assert.equal(await page.locator('#timeline').inputValue(), '5250');
await page.locator('[data-choice="silhouette"]').click();
assert.equal(await page.locator('.variant.selected').getAttribute('data-style'), 'silhouette');
await page.locator('#replay').click();
assert.equal(await page.locator('#play-label').textContent(), 'Pause');
assert.ok(Number(await page.locator('#timeline').inputValue()) < 100, 'replay restarts');
await page.locator('#play').click();
await page.locator('h1').click();
await page.keyboard.press('Home');
await page.keyboard.press('ArrowRight');
assert.equal(await page.locator('#timeline').inputValue(), '100');
await page.keyboard.press('Space');
assert.equal(await page.locator('#play-label').textContent(), 'Pause');
await page.keyboard.press('Space');
await page.setViewportSize({ width: 390, height: 844 });
await page.screenshot({ path: new URL('checks/mobile.png', import.meta.url).pathname, fullPage: true });
assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'no horizontal overflow on mobile');
await page.emulateMedia({ reducedMotion: 'reduce' });
await page.goto(new URL('buddy-comparatif.html', import.meta.url).href);
await page.waitForLoadState('load');
assert.equal(await page.locator('#timeline').inputValue(), '0', 'file opens paused with reduced motion');
assert.equal(await page.locator('[data-scene]').count(), 3, 'standalone file works offline');
assert.deepEqual(errors, []);
console.log(JSON.stringify({ errors, panels: 3, renderedContactSamples: 104, checks: ['ink/nib', 'seek', 'pause', 'play', 'replay', 'quarter speed', 'chapter', 'selection', 'keyboard', 'mobile', 'reduced motion', 'offline file'] }));
await browser.close();
